### PR TITLE
Create Azure disk using the disk sku with request volume type

### PR DESCRIPTION
**Pull request by NishanthSpShetty**
# Description

Allow user to choose azure disk SKU by sending the volume type in request

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# why

# How Has This Been Tested?

Create volume by passing
- invalid volume type, expected error.
- valid volume type, expected successful disk creation

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by sid255 — APPROVED** [review]
LGTM

**Review by sid255 — APPROVED** [review]
LGTM

**Comment by sid255** [comment]
Can we add standard ssd as default?

**Comment by NishanthSpShetty** [comment]
> Can we add standard ssd as default?

We can, in that case we wont error out on invalid type. I did think of having defaults but if we provide default its easy to make errors in type and end up using the default. Might throw off user into using something completely different and unaware off too.

**Comment by sid255** [comment]
LGTM

**Pull request merged**
