### PR TITLE
add resource URI for a disk operation

### PR DESCRIPTION
**Pull request by NishanthSpShetty**
# Description

Snapshot resource URI is missing in response when they are created in spawner and use SSD to create a disk

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# why
- Create a snapshot and return the snapshot URI of the azure resources.
- CreateVolume using existing snapshot (restore)
- remove error field in response, rpc method has second return value which is error. 

# How Has This Been Tested?

- manually tested creating empty disk
- tested by restoring snapshot with the new volume

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by SscSPs — APPROVED** [review]
lgtm

**Review by sid255 — COMMENTED** [review]
So we get `snapshotid` and `snapshot uri` from Azure? But we only use the URI?

**Comment by sid255** [comment]
> So we get `snapshotid` and `snapshot uri` from Azure? But we only use the URI?

We are

**Comment by sid255** [comment]
Closed by mistake.

**Comment by sid255** [comment]
In the requests we are we are passing snapshotid and snapshoturi (which is a provider-specific term) we should probably create `awsSnapshot`, `azureSnapshot` and add a field snapshot as `oneof` those two.

**Comment by SscSPs** [comment]
> we should probably create awsSnapshot, azureSnapshot and add a field snapshot as oneof those two.

that will add an additional layer of knowing provider/vendor-specific implementation

**Comment by NishanthSpShetty** [comment]
> In the requests we are we are passing snapshotid and snapshoturi (which is a provider-specific term) we should probably create `awsSnapshot`, `azureSnapshot` and add a field snapshot as `oneof` those two.

both aws and azure has id for a resources, URI is something to locate resource outside the bound of givent current context in azure, so we need.
making it different would confuse further with other provider too. So kept it as is. So user will set both id and uri where it is available.

**Comment by sid255** [comment]
LGTM

**Review by sid255 — APPROVED** [review]
LGTM

**Pull request merged**
